### PR TITLE
apply voice matching branch , and edit init.txt

### PR DESCRIPTION
**Pull request by P-Chang**
Finished tomitake scene.

and changed flag rule:

0 = 100%-Original
1 = Added Scene(like Miyuki, and I know the scene of introduce Natsumi)
2 = Minor change of mob character dialog(Police, Politician, Villager), and Main character's nickname (like KeiKei and Keiichi-san, RenaRena and Rena-san(Satoko)), and tone change(like 傾注傾注 and 傾聴傾聴(Mion)).
**3 = Apply Minor Change that don't have rule in 1,2,4,5**
4 = Sexual, Legal, Political, Coppyright issue
5 = Violence.

### CODE REVIEW

**Comment by enumag** [comment]
I thought you didn't want the additional files. Did you change your mind?

**Comment by P-Chang** [comment]
Sorry, please more detail easy English. I can't find my fault.

**Comment by enumag** [comment]
https://github.com/07th-mod/tatarigoroshi/pull/34#issuecomment-330727988

From that I thought you wanted to keep the branches in one file and use `ModCallScriptSection`. Here I see separate files.

**Comment by P-Chang** [comment]
it seems like my old description was not enough and my English was really bad.

First:
I planned writing branch in "tata****.txt" and stop it.

Second:
I planned separating all dialog like one dialog have one file with `CallScript`, and stop it. it really increase file number.

Third-Final:
I planned separeting all dialog and, putting original text to file1, putting console dialog to file2. 
And I made `ModCallScriptSection` that it be able to call another file function for making it possible.

I can combine file1 and file2, but it is not easy to read.

Or You want make this like it ?
```

void main()
{
main game codes
}

void dialog001()
{
changed line
}
```

**Comment by enumag** [comment]
Oh. Thanks for explaining, that's alright too.

Can you explain your naming convention?

```
ztata_009_vm03_n01.txt
```

- `vm03` - ???
- `n01` - ???

**Comment by P-Chang** [comment]
I am relieved to hear that. Another plan is really terrible.

vm = VoiceMatchingLevel
n = Number

I would like to one chapter dialog to one file, but if there are ton of changing, it need second file.
so, added number in filename just in case.

If these files are Effect or Animation files
ztata_009_ee02_n01.txt

I named these to bit strange for differentiation.

And sometimes one file have various flag value dialog.
In this case, I'll name it to ztata_009_vm0x_n01.txt

**Comment by enumag** [comment]
Cool. I'll just replace the init.txt file with my better formated version and merge this. Thank you!

**Comment by P-Chang** [comment]
Oh, Thanks.

Would you change GEffectExtendMaxNum to 0 too?
It doesn't have effect brach, I forgot it. 

And change GMOD_DEBUG_MODE to 0 before releasing please.

**Comment by enumag** [comment]
On a second thought I actually like your init.txt. Let's go with that. Thank you!

**Comment by enumag** [comment]
> I know the scene of introduce Natsumi

@P-Chang Which chapter are we talking about here?

Out of the 6 possible values for GCensor, which one is default? I guess 6 since we don't want to censor the game?

**Comment by P-Chang** [comment]
You mean 6 as 5?
But I used greater in branch, 6 is same as 5.

2 or 3 are middle state, so I prefer these. but I'll have no objection for your choice.
But we should not use value that is not implemented as default in my opinion. 

You treat 5 as default when I make branch of 5, I have no objection for it.

**Comment by enumag** [comment]
Yep I meant 5. @ItaloKnox and @Grelo very much prefer to not censor the game so 5 as default should be the way to go I think.

Which chapter has the scene to introduce Natsumi? Is it something we should port from the console versions?

**Comment by P-Chang** [comment]
You probably misunderstand flag rule, 5 have all censorship.
0 is same as original text line.

0 use only 0
1 use 0,1
2 use 1,2 and some of 0
3, use 1,2,3 and some of 0
4, use 1,2,3,4 and some of 0
5 use 1,2,3,4,5

0 = 100%-Original
1 = Added Scene(like Miyuki, and I know the scene of introduce Natsumi)
2 = Minor change of mob character dialog(Police, Politician, Villager), and Main character's nickname (like KeiKei and Keiichi-san, RenaRena and Rena-san(Satoko)), and tone change(like 傾注傾注 and 傾聴傾聴(Mion)).
3 = Apply Minor Change that don't have rule in 1,2,4,5
4 = Sexual, Legal, Political, Coppyright issue
5 = Violence.

is my plan

Oh, I missed Natsumi scene. Finding exactly location is bit difficult.
Keiichi and Mion and Rena meet Natsumi in 7th mart. but there are no scene that
they go to 7th mart together. If I or someone find suitable location, I'll add.

https://www.youtube.com/watch?v=MFk6MCa3TS8&list=PLff23ljXjapPzC0RhTVGbFdgs9x8xJZzH&index=1#t=40m0s

**Comment by enumag** [comment]
Oh I totally misunderstood that. You're right, 2 or 3 should be default.

Do you know which console chapter is it from? Or is it from the common route prequel? Maybe it should be in Someutsushi somewhere but I'm not sure since I have yet to read it.

**Comment by P-Chang** [comment]
Probably my description was bad.

It is in prequel. Someutsushi start from same prequel, but @DoctorDiablo version doesn't have prequel. and prequel is not necessary. We should not take long time for this scene. Let's leave it until someone find good location.

**Comment by enumag** [comment]
@P-Chang The directory for voices... should it be named "voice" or "Voice"? It is important for linux since it has case sensitive file names.

**Comment by P-Chang** [comment]
Probably, it is "voice". small character is used in DLL.

**Comment by enumag** [comment]
@P-Chang I think you made a small copy-paste mistake. I tried to fix it using Italo's translation. Can you check? https://github.com/07th-mod/tatarigoroshi/commit/f10729b7f9195facb11d53243c269a52c0856c5e

**Comment by P-Chang** [comment]
Oh, It's my fault. And I missed Tomitake name, Thank you and sorry.

**Comment by enumag** [comment]
Don't worry about it, I just wanted you to check if it is ok now. Thanks you!

**Pull request merged**
