### PR TITLE
Adjustment for auto mode

### PR DESCRIPTION
**Pull request by P-Chang**
This is skipable wait time for scene that use "t_ep~.png".
The default waiting time is too short and it is hard to read because it is hidden in the text box, so I set a skipable wait time.

Alphaimage.png is just invisible image file.
It only draws a invisible image for 10 seconds after the original processing.

It will fade to black so it does not disturb the text box.
In console, texts moved to the center, but I think that erasing is easier to read.

Actually I want to use "WaitForInput", but I could not find it for the image files.
If you know it, please replace.

Also I am not confident that I have been told accurately. Sorry for my broken English.

### CODE REVIEW

**Comment by enumag** [comment]
You can use WaitForInput like this:

```
OutputLineAll(NULL, "", Line_WaitForInput);
```

I was actually trying to eliminate all auto-mode instances from the games a while back. Apparently I missed this case.

Also your english is not that bad. ;-)

**Comment by P-Chang** [comment]
Oh, thanks. I remade it.

**Comment by P-Chang** [comment]
@enumag 
I tested it like this


	DisableWindow();
	DrawScene( "black", 1000 );
	DrawScene( "t_ep8", 1000 );
	SetValidityOfInput( FALSE );
	Wait( 1000 );
	SetValidityOfInput( TRUE );
	OutputLineAll(NULL, "", Line_WaitForInput);
	DrawScene( "black", 1000 );

	PlaySE(4, "s03/01/140101174", 128, 64);
	if (AdvMode) { OutputLine("<color=#956f6e>圭一</color>", NULL, "<color=#956f6e>Keiichi</color>", NULL, Line_ContinueAfterTyping); }
	OutputLine(NULL, "「…絶好調だった当時の俺なら、次の朝までには必ず死んでる。",
		   NULL, "\"...If I'm in top form like I was then, you'd die before tomorrow morning for sure.", 


Certainly, game waits for next dialog. but text box overwrite the image.
Any solution for it?

**Comment by enumag** [comment]
Oh... Nope, unfortunately there is no solution to that. In that case I think the patch you posted earlier is good enough. Also you can remove these.

```
SetValidityOfInput( FALSE );
Wait( 1000 );
SetValidityOfInput( TRUE );
```

**Comment by P-Chang** [comment]
@enumag 
OK.

And I think this wait is necessary for someone like me that excessive clicker.
It has no log and easy to skip accidentally. Scene that uses "wait" is really sluggish but 1 second is not big time in this case.

**Comment by enumag** [comment]
Ok then. Thanks!

**Pull request merged**
