### PR TITLE
Updates by @Grelo

### PR DESCRIPTION
**Pull request by enumag**
This is a pull requests for the CGs update that @Grelo made for us.

@Grelo I see you've removed quite a bit of character sprite transitions especially in tata_001.txt. Is that intentional? Like to match the voices or something?

Also one minor thing. If you decide to work on future episodes as well could you put the weather images and character sprites into separate directories sunset/night/rain and not suffix tham with _a or _b - same as Guraman did for the previous episodes? It will make some things easier for me later on. Don't worry about Tatari though.

Also I added you to credits as well. ;-)

### CODE REVIEW

**Comment by Grelo** [comment]
@enumag I think no, my only intention was to add cgs, sprites for characters who didnt have ones and replace some original bgs and sprites to match weather and if something got in the way of cgs delete it......

I had some problems with sprites appearing in the same moment like tomita and okamura when they both appear on screen cause i didnt know how to do  so u can fix it.

As for everything else i think its my mistake not to know about scripting so u can fix that too...thanks.

**Comment by enumag** [comment]
@Grelo Alright, I'll revert some of the changes and test it all during my playthrough.

As for Tomita and Okamura I'll look into it when I get there. If it won't work correctly I'll just copy Guraman's code from Oni/Wata.

**Comment by enumag** [comment]
@Grelo Checked it again and I can say you've clearly made the changes intentionally and they are correct. It's the cases when characters are already on the background CG so you don't need the sprites. I guess there won't be much for me to fix after your excelent work. :+1:

**Comment by Grelo** [comment]
@enumag thanks. :) I will look on Himatsu tommorow.

I have question, do you want a basic graphic mod like doctordiablo made first or later with full mod.

And if u know which font guraman used for his scenario images it will help with creating them, i can make one for onikakushi too, thanks

**Comment by enumag** [comment]
@Grelo Actually @DoctorDiablo just finished the basic patch for Himatsu (https://github.com/07th-mod/himatsubushi/issues/1#issuecomment-254014542). However @ItaloKnox did not finish his work yet so I think you should wait until he does.

I don't know what font it is but I'll try to run Guraman's images through some font recognizing software.

**Comment by Grelo** [comment]
@enumag Ok ill wait then.....thanks for help with font.

**Comment by enumag** [comment]
@Grelo Recognizing the font won't be easy. I tried several tools but couldn't find a match. The simple ones where you upload the image were confused that the font was bold white with shades and couldn't provide any useful result. Then I tried something more advanced where you describe a font by features of certain charactes - but we don't have enough samples of uppercase letters and numbers for that.

Then I've found something you could try: https://helpx.adobe.com/photoshop/how-to/match-font-image.html

When photoshop shows you some results pay close attention to some of the specific features of the font. Like lowercase e and c are almost closed on the right side and their lower part is bolder than usual.

**Comment by enumag** [comment]
Maybe it's just some variant of Times New Roman - it certainly is very similar. Perhaps Guraman just condensed it or something.

**Comment by enumag** [comment]
I've tried some more tools and searched between fonts similar to Times New Roman. My best guesses at the moment are either Times New Roman itself, Pelham DT or Newton.

**Comment by Grelo** [comment]
@enumag Ok thanks will look at it later.

**Pull request merged**
