### PR TITLE
[WIP][help wanted] Chapter 4 fixes

### PR DESCRIPTION
**Pull request by enumag**
Don't merge this yet. I only went through first half of the chapter.

Aside from #19 there are two more things I need some help with.

1. On line 2108 the voice file is incomplete - it only says "Satoko" instead of "Satoko's happy." - I was unable to find the correct file.
2. Look to lines 2426 and 2429 where I added some missing voices. I'm not sure if the voice is actually saying the text that is used there, I matched it by file numbers.

### CODE REVIEW

**Comment by ItaloKnox** [comment]
These two voices are saying something completely different. I think it's one of the PS3 changes, though I don't think we should translate it right now.

Now, about Satoko it's one of those weird cases where japanese makes sense but english also does. Keiichi says (literal translation): "`L2106` (she) is happy. `L2109` Satoko."
I'm unsure if changing the translation would be good enough. It makes sense in japanese, but in english it doesn't sound quite right. Maybe you can come up with something better.

**Comment by enumag** [comment]
Why not translate them? I thought we wanted to use the PS3 changes in most cases. Even more so if it's required for the voices.

For the Satoko happiness lines - should I try to combine both lines into one? I think I can set a wait to make the second file play right after the first without waiting.

**Comment by ItaloKnox** [comment]
In cases like this I'm not really confident in translating the lines. But well, fuck it. Might have slipped something, but that's what I can come with:

```
S19/06/500600356    「あ、『プリティ』と『ぷりちー』は似てるようで微妙に違いますからね。
Oh, "pretty" and "purity" are really hard to differentiate, right?               # should be something along the lines of being "pretty similar", thus becoming hard to understand

S19/06/500600357    日本の侘び寂をミックスした和洋折衷の言葉なので、注意してください」
Be careful with mixing refined japanese words and english together.
```

These aren't easy lines to fix and I feel like I'm not extracting 100% from them, in any case the other translator will retranslate this stuff later (god knows when).

So, about Satoko, this is a good idea. I think it works better than what we have right now.

**Comment by enumag** [comment]
Thanks!

**Comment by enumag** [comment]
Actually I'm still not finished with chapter 4. But ok, I'll make a separate PR for the second half.

**Comment by ItaloKnox** [comment]
Oh, my bad. I thought you were done. Shouldn't be a problem since I'm not pushing a new version anytime soon.

**Pull request merged**
