### PR TITLE
Add automated voice lines

### PR DESCRIPTION
**Pull request by enumag**
The script uses several methods to match the voice lines to the script. It is just a first draft though so I need a feedback:
- Are there any missing lines you think the script should be able to insert?
- Did the script insert any lines where it should not have insert anything?
- Did the script insert a wrong voice file anywhere?
- Is there anything else the script should fix?

Also I'd like to aim for this script to be better than the old one. So don't restrain your requests to what the old script did.

Output from the current version of the script:

```
Inserted 189 voice lines to omake_03.txt.
Inserted 610 voice lines to tata_001.txt.
Inserted 599 voice lines to tata_002.txt.
Inserted 672 voice lines to tata_003.txt.
Inserted 597 voice lines to tata_004.txt.
Inserted 410 voice lines to tata_005.txt.
Inserted 563 voice lines to tata_008.txt.
Inserted 14 voice lines to tata_008_02.txt.
Inserted 338 voice lines to tata_009.txt.
Inserted 176 voice lines to tata_009_02.txt.
Inserted 115 voice lines to tata_010.txt.
Inserted 143 voice lines to tata_010_02.txt.
Inserted 57 voice lines to tata_010_03.txt.
Inserted 149 voice lines to tata_010_04.txt.
Inserted 40 voice lines to tata_011.txt.
Inserted 60 voice lines to tata_011_02.txt.
Inserted 149 voice lines to tata_011_03.txt.
Inserted 589 voice lines to tata_012.txt.
Inserted 28 voice lines to tata_013.txt.
Inserted 326 voice lines to tata_013_02.txt.
Inserted 83 voice lines to tata_014.txt.
Inserted 0 voice lines to tata_ep01.txt.
Inserted 108 voice lines to tata_ep02.txt.
Inserted 54 voice lines to tata_tips_01.txt.
Inserted 38 voice lines to tata_tips_02.txt.
Inserted 73 voice lines to tata_tips_03.txt.
Inserted 47 voice lines to tata_tips_04.txt.
Inserted 1 voice lines to tata_tips_05.txt.
Inserted 33 voice lines to tata_tips_06.txt.
Inserted 0 voice lines to tata_tips_07.txt.
Inserted 0 voice lines to tata_tips_08.txt.
Inserted 0 voice lines to tata_tips_09.txt.
Inserted 0 voice lines to tata_tips_10.txt.
Inserted 0 voice lines to tata_tips_11.txt.
Inserted 0 voice lines to tata_tips_12.txt.
Inserted 0 voice lines to tata_tips_13.txt.
Inserted 0 voice lines to tata_tips_14.txt.
Inserted 17 voice lines to tata_tips_15.txt.
Inserted 21 voice lines to tata_tips_16.txt.
Inserted 20 voice lines to tata_tips_17.txt.
Inserted 0 voice lines to tata_tips_18.txt.
Inserted 0 voice lines to tata_tips_19.txt.
```

If you're satisfied with the results create a new repository for me to push the script source code there.

### CODE REVIEW

**Comment by ItaloKnox** [comment]
Looks fine overall. I would say it catches more stuff than the previous script, and the stuff I could see that needed to be fixed is just the Levenshtein distance threshold being followed. Not a big deal at all, this happens when you have a dialog broken into three voices, and the middle voice is the one where it matches _less_ than the others.

Anyway, I'm accepting this one here. Thank you for you hard work!

**Comment by enumag** [comment]
Glad to help! I went over your commits and commented on [some](https://github.com/higurashi-mod/tatarigoroshi/commit/433dbdbdef6cc136d46b077f1af29c465bb19ada#commitcomment-18117267) [lines](https://github.com/higurashi-mod/tatarigoroshi/commit/9666386b2d73ae729f70029518c2bd2ec5f1aae9#commitcomment-18117317) - these are just notes for myself. Your last comment here mentions one of those as well. I'll fix these issues in my script so you won't have to deal with them for future chapters.

I probably won't have time to look over all of your commits but if you find more cases that could be improved for the future, let me know. There will be a lot more Higurashi chapters in the future so fixing such issues now is definitely worth it. (It is easy for me to fix these bugs.)

If you want I can re-run the script for Tatari as well and commit only those files you didn't get to yet.

Also do you want the source code?

**Comment by ItaloKnox** [comment]
For now I'll be working with the tips files, so if you manage to fix the points you took note of, be free to run the script again on the main files. You _don't_ have to, but every improvement is welcome.

Also you've been around for quite a while, so I don't think you'll be just gone like the other guy, hahaha. If you upload your code to github, just tell me so I can keep an eye on it. Actually I'm fairly interested on how you did it.

**Comment by enumag** [comment]
I thought we should create a repo for it within this organization. Or do you not want it here? I don't mind either way.

I'm not planning to disappear any tiime soon. You won't get rid of me so easily. :-P

**Comment by ItaloKnox** [comment]
I thought you might want to keep it on your account, but having one right here would be awesome. I'll take a look around and give you proper permissions to push your own repo inside the organization (I'll also need a name change because of Umineko).

Well, the last thing I would want is to get rid of you. I hope you'll stick around until the very last chapter.

**Edit**: here we go, I think you should be able to create your own repos inside the organization now. :)

**Comment by enumag** [comment]
My GH account is already so messed with forks of open-source projects that I actually prefer to put the important repos to organizations.

I see you've already renamed the organization - to the very name I wanted to suggest. :-)

**Comment by enumag** [comment]
@ItaloKnox I've updated the main files using the updated script.

https://github.com/07th-mod/tatarigoroshi/commit/5eeb240a11bffbd2774c238e767470414bc62c3f

**Pull request merged**
