### PR TITLE
Fix tata_008

### PR DESCRIPTION
**Pull request by enumag**
@ItaloKnox Can you check if the text matches the added voices? I pulled them from PS2 based on file numbers but I'm not completely sure what they say.

### CODE REVIEW

**Comment by enumag** [comment]
@ItaloKnox Damn there is an awful lot of voices missing and most if not all of them indeed are among the PS2 files. I don't know how you're doing it for every chapter. It takes a lot of time.

**Comment by ItaloKnox** [comment]
I guess you just got to one of those problematic parts. When I said that your change to add empty PlaySE lines before dialog saved *a lot of time*, I wasn't exaggerating. Some places take so much time you could finish half a script in the meantime...

Anyway, give me a couple minutes to check the japanese lines.

**Comment by enumag** [comment]
Well I'm not really finished yet, there are at least a dozen more missing voices, probably more. Maybe I should separate the algorithm for adding placeholders, run this script through that and and have you look at them? It could be faster then this hell and we might need to do the same later with other scenes so separating the algorithm could be good in the long run. What do you think?

**Comment by ItaloKnox** [comment]
You almost got a perfect score. ``s03/03/140300082`` doesn't match. I don't know if we can change the text or not because it really doesn't seem to be related to what Mion's talking about. She talks about Satoko instead but this change makes no sense at all...

**Comment by enumag** [comment]
Hmm possibly that voice should be used somewhere later and the line where I used it is indeed unvoiced?

**Comment by ItaloKnox** [comment]
It's definitely not covered by the previous voice, so maybe it was really unvoiced in the game. Or they actually changed the text even though it makes no sense at all to change it.

I can't really grasp what they're talking about Satoko there, but I'll try to get some confirmation before pulling the trigger.

**Comment by enumag** [comment]
Well the scene is about Keiichi speculating to use the same reason why Rika is able to live alone to get Satoko away from Teppei. So it's not odd that they're talking about Satoko at all.

**Comment by enumag** [comment]
Anyway you might have missed one of my comments above I think? (You didn't react to my question there.)

**Comment by ItaloKnox** [comment]
Oh, sorry, I really missed it.

I think anything is worth a try, if you think it'll be worth the time coding it, it won't hurt to try. I have nothing against it, just instruct me later on what we'll have to do.

Also now the voice makes a lot of sense. I just realized she said 居候 (isourou - freeloader), so what you said about the context makes sense. I'm waiting for confirmation on the translation, but I more or less know what she's saying now.

**Comment by enumag** [comment]
Alright then. I'll try to do my coding part and get back to you later. Thanks. :-)

**Comment by enumag** [comment]
I wrote the script to add placeholdes. It added about 600 of them throughout the whole tatarigoroshi chapter. Well that was way too much and I could see myself that many are false-positive.

So I limited it to just lines that have a starting quote - that means that there is only one placeholder at the begining of a paragraph but throughout the paragraphs there may actually be several voices missing. But since such lines would be immediately below I think you'll see them.

EDIT: If it is not clear what I mean, see [this example](https://github.com/07th-mod/tatarigoroshi/blob/81e5f5c22c1cfd9f8e8f8c3c0323a753bca54391/Update/tata_008.txt#L2777-L2796) - there is only one placeholder at the beginning but probably about 4 or more missing voices.

With this limitation the script added about 130 placeholders throughout Tatari. I checked them for obvious false-positives but they all seem legit to me.

Can I ask you to look into it? I pushed it into the placeholders branch. I made sure it would not contain any placeholders for voices we already added today either in master or in this pull request.

https://github.com/07th-mod/tatarigoroshi/commit/81e5f5c22c1cfd9f8e8f8c3c0323a753bca54391

No need to rush with this, just take your time. And tell me if there is something else I can help you with. Preferably start with tata_008 as that's where I'm now with my proofreading and I don't want to continue until we deal with this.

**Comment by enumag** [comment]
For comparison I tried to run the script on Hima which has already gone though my proofreading. It only added 12 placeholders throughout the whole chapter so I believe Tata really is buggy like that - after all there are just a few in the parts of Tata I already went through but many in the parts I have yet to read.

EDIT: Oh and you don't need to worry about adding the names. It may take me a few hours to write a script for adding them after ADV compilation but I can do it. And we will probably need it for Tsumi anyway.

**Comment by ItaloKnox** [comment]
Okay, gotcha. I'll try to start them today. I suppose it's the placeholders branch, right?

Anyway, let me work through this pull request first:
```
	PlaySE(4, "s03/03/140300082", 128, 64);
 	OutputLine(NULL, "…孤児院って言うか、児童擁護院のことだけど。」",
 		   NULL, " ...Actually, it would be child and family services, not an orphanage.\"", Line_ModeSpecific); 
```
Should be:
``都子はそこに居候してるってことになるけどね。」``
``But Satoko is actually living there as a freeloader."``

You can adapt it, you know how the magic works. Commit and merge it for me when you think it's good enough. 👍 

I'll see if I can fix some of the scripts in the meantime.

**Comment by ItaloKnox** [comment]
Oh, btw, you can also change the "but" to a "however", I think it works better.

**Comment by ItaloKnox** [comment]
That was [a lot more crazier](https://github.com/07th-mod/tatarigoroshi/commit/8dfac0b7cbf1808c22ba4f8bf9c883c9075dd2c7) than I expected...

I still haven't found around 10 of them. Please check it out when you have the time, I'll keep going to see if I find anything else in the next chapters.

**Comment by enumag** [comment]
Wow you are fast! Also 100 voices in tata_008 alone on top of what we fixed earlier?! That's crazy.

It seems that writing the script for adding placeholder was a really good call - better than I expected really. It would have taken me days to fix this script alone.

I'm going to work now so I'll try to write the script for adding names this evening and look over the changes on friday.

**Comment by enumag** [comment]
@ItaloKnox I screwed up. :-( I wrote the script to add the names but it doesn't work. After debugging it for a while the reason is obvious - since the voices were not in the PS3 script I don't have them in my database so the script can't figure out the names. So unless you have a PS2 script somewhere we will have to add the names manually.

**Comment by ItaloKnox** [comment]
Can't you use the folder number as the input? The voices are separated by character (s03/03 = Mion, s03/02 = Rena, etc), so maybe you can feed it a list and have it put the names by reading the PlaySE in the previous line (or next, I think I actually broke the pattern without knowing).

**Comment by enumag** [comment]
Hmm actually maybe not. While what I wrote earlier is true, it seems there is a way. It turns out that each charachter has voices in different directory.

s03/01 - Keiichi
s03/02 - Rena
s03/03 - Mion
s03/04 - Satoko
s03/06 - RIka
s03/10 - Irie

So I should be able to match them using these. I just hope these rules will still apply when you add more.

**Comment by ItaloKnox** [comment]
I guess we're in sync, then! ahahaha

**Comment by ItaloKnox** [comment]
Oh, by the way, I think you should commit the translation change [I posted above](https://github.com/07th-mod/tatarigoroshi/pull/29#issuecomment-316543439) and move what we're doing now to a issue. Maybe it's better for archiving purposes?

**Comment by enumag** [comment]
lol looks like we figured out the same thing. :-)

Also one thing I want to warn you about. Do not merge the placeholders branch into master. With so many voices the repository gets large and takes longer to clone. Instead when you're done, add the voices to the voice patch and let me do some git magic to keep them out of master.

Don't worry, I did not forget about the translation. ;-) I think we can keep the discussion here. I won't merge this PR for the same reason I wrote above.

**Comment by ItaloKnox** [comment]
Makes sense. I actually thought about that after doing the whole script, the only reason why I pushed them was because I thought you would want to test it. I'll release a new voice patch right after we finish this stuff. 👍 

That said, the only issue is merging it into master, right? That's something I also want to avoid. Guess there's no issue if I keep pushing them into the placeholders branch?

**Comment by enumag** [comment]
Exactly. Pushing them to a branch we will delete later is fine - and might actually help me with adding the names. :-)

**Comment by enumag** [comment]
I just comitted the [names](https://github.com/07th-mod/tatarigoroshi/commit/8b3dc5c5e4cfc43c10a2935dd408ebe860feac71) and the [translation](https://github.com/07th-mod/tatarigoroshi/commit/a52a9ac64726c668c7af08898e24600ddf500a3a) we discussed earlier.

Now I'm going to read tata_008 in the game to see if there is anything else to be fixed. You did great work with the voices!

**Comment by ItaloKnox** [comment]
Thanks a lot! Don't forget there's still a few missing voices in tata_008, and after going through the remaining scripts, there's also a few in 009, 010_03 and maybe one or two in a random script. Shouldn't be more than 15, I guess. Maybe I didn't look enough, but I really couldn't find them.

Your turn now, just call me if you need anything. :)

**Comment by enumag** [comment]
Awesome! 15 is very few compared to the 200 or so which were missing until now. :-) Thank you!!

Can you upload the new voice pack for Tata with all the voices from this repo? (Knowing you I kind of expect an "I already did" answer here. :-P)

Also I think you will want to hold off the ADV-mode release for Tata until I sort this out. I'll let you know when I'm done. You can go ahead with Hima though.

On another note I'd like to try using the placeholders insertion script on the other chapters and have you check the placeholders for PS2 voices which were cut out on PS3. I expect the other chapters to be in a lot better state than Tata though so it should not take too long. Can I prepare this for you?

**Comment by ItaloKnox** [comment]
I didn't yet because I need to use my server for this, but I'm already working on it and it should be finished in a few minutes. 😁 

Also yeah, I'm holding off while we're working on this. Everyone can still grab the ADV Mode if they want, so it won't hurt to hold off a bit while we fix the problematic stuff. I'll release Hima and Meakashi together tomorrow.

And sure, go ahead and prepare them. Are we going to do this starting from Onikakushi again?

**Comment by enumag** [comment]
Ehm... You might want to hold the voice patch actually. I need to verify if it applies to all of them but it seems that the voices pulled from PS2 have much lower volume and do not fit in so well. So we will probably need to amplify them first.

**Comment by enumag** [comment]
Yep, it's all the new voices. And a fun fact too. Rena's PS2 voices are noticeably lauder than voices for the other characters - but still quieter than PS3 voices. Not sure if this fact important for fixing - it depends on whether the bulk amplification will be relative to the old files or not. Some sort of volume normalization might work better?

I think I found some guide how to do bulk amplification with Audacity few days ago. But you said you had some audio experience, right? So you would probably have a better result than me?

**Comment by ItaloKnox** [comment]
If you can get me a couple of audio samples I can try to find the volume difference between them. This way we can change the volume of the PS2 voices through the script and have them be closer to the PS3 voices. Actually processing each file have a few issues:
* it will take a really, really long time
* the audio quality will drop because we don't have lossless files

Processing each file manually will give us a 1:1 file but this will drag on for a long time, I think we'll get results faster by changing the in-game volume to make it at least closer. **OR** perhaps we can try to ReplayGain the whole voice pack? I don't know if the engine supports it, but as far as I know it's just metadata and maybe worth trying.

**Comment by enumag** [comment]
Wait there is a way to change the volume for individual files in the script? How?

I don't think it would take that long. We're talking about really small files, not songs or anything like that. I didn't mean to process the files one by one, just to do some bulk amplification for all of them. But alright, whatever you prefer.

I have no idea what ReplayGain is so you lost me there.

As for samples, do you have the voices on your local PC? You can just open the directory with this repo to see the newly added voices. In a second window open your StreamingAssets/SE directory.

For example you pulled s03/03/140300035.ogg from the PS2. So find 140300035.ogg in the repository and 140300034.ogg and 140300036.ogg in the game files. You'll hear the difference.

**Comment by ItaloKnox** [comment]
``PlaySE(4, "s03/04/140400198", 128, 64);``
Wasn't the ``128`` the sound volume? I remember this back when the project was still starting and the guy who did the first version of the automated script used ``256`` instead. It was double the volume, as far as I remember. It was a long time ago so maybe I'm not recalling it correctly, I guess?

To be simple, ReplayGain is some sort of normalization algorithm but the purpose is to make music mastered at different peak levels normalize up or down. So, in short, if we pick all the voice files and use ReplayGain in them, it should normalize the entire thing together.

Usually I dislike ReplayGain, but in this case it might work. Instead of reencoding the file, it produces a metadata tag to adjust the loudness, and this is better because the quality won't drop. We also avoid clipping this way. Check [rgain](https://bitbucket.org/fk/rgain), it should work nicely for us.

**Comment by ItaloKnox** [comment]
Oh, here, [check it out](https://github.com/07th-mod/onikakushi/commit/c1b3e3070275e77679907e8f8a071f3e0d18cd59). I think I'm not crazy after all.

Though at least for me I can't remember how much louder it was. I actually use audio monitoring hardware on my PC so everything is *too loud*. I can honestly leave the game playing on auto mode and hear my headphones a couple rooms away, so this change wasn't really meaningful for me.

**Comment by enumag** [comment]
Oh. I wasn't around back then so I had no idea. Thanks for sharing, I might use it in some cases to reduce or amplify volume of some songs or sound effects. The volumes are not consistent at all since the audio files come from several different sources.

For this issue it could work to just change the volume for these files in the script. But in order to do it automatically I'll need to separate the files based on their sources. Maybe like this?

```
SE/s03/01/<ps3voice>.ogg
SE/ps2/s03/01/<ps2voice>.ogg
```

I could then write a script to adjust the volumes based on the directory.

**Comment by ItaloKnox** [comment]
Well, looks good for me. The only issue would be to adjust the scripts, but that's not a big deal. I suggest going for ``SE/ps2/01/<ps2voice>.ogg``, though it would be an "issue" when the file was from s19 or another folder. Or not, actually, since we've been only taking the voice files we need instead of the whole folder for some time already. The structure respects the character folders (01 = Keiichi) for all ``s**`` folders.

**Comment by enumag** [comment]
I somehow feel that droping the sXX information entirely might cause some unexpected issue later. I'd really rather keep it. Maybe `SE/ps2sXX/01/<ps2voice>.ogg`?

**Comment by ItaloKnox** [comment]
Let's not overcomplicate it. 😆 
``SE/ps2/s03/01/<ps2voice>.ogg`` was already good enough. :)

**Comment by enumag** [comment]
I added the ps2/ prefixes. Now to make the script that will replace the volumes - that will be easy to be honest. The difficult part here is to determine the right volume number. I hate these trial & error stuff when every attempt means close the game, make the change, delete CompiledUpdateScripts, run the game, click through the menu, load the game and start over. :-/ Can you think of any easier way to get the right number?

**Comment by enumag** [comment]
@ItaloKnox Would you be able to split this file to two? It would be better to have the "What's this?" part separate.

https://www.dropbox.com/s/dpq7fwbfd38sffc/140200066.ogg?dl=1

**Comment by ItaloKnox** [comment]
Professionally done™. Sorry I didn't catch this earlier, I wasn't home yet. 😄 

[140200066.zip](https://github.com/07th-mod/tatarigoroshi/files/1167639/140200066.zip)

**Comment by ItaloKnox** [comment]
Oh, also sorry I didn't see the previous comment. I think I can calculate the volume difference but honestly I'm not sure how I would translate that into the game engine. If it was a 0~100 meter it would easy, but it seems to be way worse than that.

Edit: also, is every voice using a different volume? I mean, are some louder or quieter than others? Excluding the Rena case, of course.

**Comment by enumag** [comment]
The files are great, thanks! No need to apologize. Also I was busy with organizing my vacation next week so I didn't really work on Tata all the time.

I first tried to calculate the number from how much volume difference I needed when playing the file in a media player. It was completely off in the game so I ended up experimenting anyway. In the end I just set all PS2 voices to twice the normal, 256 (not sure if higher values are even possible) with Rena slightly lower at 220. Now I don't really notice it when the game switches from PS3 voices to PS2 so it's ok. If you happen to come up with some better numbers later then I can easily rerun the volumes adjustment script.

**Comment by ItaloKnox** [comment]
I don't think I'm a fair metric for that, like I said before, my hardware is a little too loud. 😆 
If you think it's already good enough, let's stick with that. I trust you.

Anyway, if we end up with something more troublesome than that, I'll try to come up with something to fix the issue. Hopefully we won't ever need to directly mess with the files, it'll be hell to normalize them every time we update the patch.

**Comment by enumag** [comment]
@ItaloKnox We have two voices missing [here](https://github.com/07th-mod/tatarigoroshi/blob/placeholders/Update/tata_008.txt#L4801-L4817). I found these candidates, can you check if they match?

https://www.dropbox.com/s/i6o4m7ry6ukr7qn/141000003_004.ogg?dl=1
https://www.dropbox.com/s/me32pau6kkajzno/140400036.ogg?dl=1

**Comment by enumag** [comment]
Hmm I found some more. I'll make a commit as usual and let you know when I'm done to check them all at once..

**Comment by ItaloKnox** [comment]
```
	OutputLine(NULL, "「……自転車でこんなに買い物をしたら、運びきれませんからね。」",
NULL, "\"...She wouldn't have been able to carry all those groceries on her bike.\"", Line_Normal);
```

Both lines say the exact same thing but going with the english translation it should be Irie who's speaking, I guess.

The both above are from Satoko, 140400034 and 140400035. Dunno why I didn't find these at first.

**Comment by enumag** [comment]
Thanks. Don't be so harsh on yourself. You found 100 voices in this script only after all. I don't mind that you missed a few.

**Comment by enumag** [comment]
> Both lines say the exact same thing but going with the english translation it should be Irie who's speaking, I guess.

Well the voice I found is Irie. Is the japanese text different than english?

**Comment by ItaloKnox** [comment]
Oh, sorry, I think I wasn't clear enough. 141000003_004 should go there. 👍

**Comment by enumag** [comment]
~~What does 140400036 say then? I can't seem to find a place for it but it should go somewhere into this dialogue.~~

EDIT: Oh I see now. Stupid me. Never mind.

**Comment by ItaloKnox** [comment]
The same thing, actually. I just went by the context, which should be Irie talking since Satoko talked before. I also couldn't find where it fits, so I'm just as lost as you in this case.

To explain it better, the japanese text is gender neutral. Since it wouldn't sound really good in english, the translation pointed who's Irie is talking about. Now, Satoko says the exact same thing in her voice line, but the japanese text is nowhere to be seen. Everything before and after the comma only appears once in the script, so I don't have a clue where that is used. It would be very weird but maybe it's in other script even though it wouldn't follow the structure we're used to.

**Comment by ItaloKnox** [comment]
140400034 and 140400035 should go here:
```
	OutputLine(NULL, "「…買い物の帰りに偶然、監督にお会いしたんですのよ。",
		   NULL, "\"...I happened to run into Coach on my way back from shopping.", Line_WaitForInput);
	OutputLine(NULL, "…送ってくださるというので、お言葉に甘えたのですわ。」",
NULL, " ...He said he'd bring me home, so I accepted his offer.\"", Line_ModeSpecific);
```
And 141000003_004 should go here:
```
	OutputLine(NULL, "「……自転車でこんなに買い物をしたら、運びきれませんからね。」",
NULL, "\"...She wouldn't have been able to carry all those groceries on her bike.\"", Line_Normal);
```

**Comment by enumag** [comment]
Damn those missing Teppei lines. His voice files have different numbers on PS2 so even though I'm quite sure they are somewhere in there (because Satoko's responses to those lines are there) I can't find them. We don't have PS2 scripts available anywhere, right?

**Comment by ItaloKnox** [comment]
I don't think so. I've been doing this stuff since day 1 and we never had the PS2 scripts. We got the voices, but the scripts... nope.

I can provide the game .iso at least, but I'm terrible when it comes to this kind of thing. If you want to try your luck, I can upload it later today.

**Comment by enumag** [comment]
Not like I have any experience with that sort of things but I could try I guess.

**Comment by ItaloKnox** [comment]
I actually had it on my onedrive all along, so I imported it to my server. I think this one should be the [last version of the game](http://ichigohi.me/root/higurashi/higurashi-ps2.iso).

**Comment by enumag** [comment]
My god I feel stupid. The missing Teppei files were literally the first files in the directory - 17/142000001.ogg and 17/142000002.ogg.

I don't think I can get the scripts from the ISO. Hopefullywe won't need to.

**Comment by ItaloKnox** [comment]
Now I'm also feeling stupid for not paying attention to the folder where his other voices came from. 😆

**Comment by enumag** [comment]
First, please check the voices I added in [this commit](https://github.com/07th-mod/tatarigoroshi/commit/e5f4002d2d4cec0b5bfbfabe7b07f41a9ce5619a) - 142000005 probably needs translation fix.

The rest of missing Teppei lines are too difficult for me. I added some more [placeholders](https://github.com/07th-mod/tatarigoroshi/commit/4a364d19afe5b20b539cd649056ebf46acdd6779). Could you check these and the ones left there from before? The voices should be near the top of the `HigurashiPS2/17` directory, probably right after `142000005.ogg` but there are some voices that made it to PS3 mixed in so I'm not confident I would match them correctly.

Note for myself: need to rerun the volume adjustment script later.

**Comment by ItaloKnox** [comment]
Found some. Won't commit them because I think you might want to adapt it better.
```
	PlaySE(4, "ps2/s03/17/142000005", 128, 64);
 	OutputLine(NULL, "　ボケぇッ！！」",
 		   NULL, " Idiot!!\"", Line_ModeSpecific); 
```
Japanese: ``どうしようてんじゃ！？``
English: ``So what'll you do!?`` (or "what can you do about it", should sound "delinquent-ish")

```
	PlaySE(4, "ps2/s03/17/142000003", 128, 64);
 	OutputLine(NULL, "「ボケがぁッ！！",
 		   NULL, "\"You idiot!!", Line_WaitForInput); 
```
Japanese: ``やかましいわ！！``
English: ``Shut up!!`` (can be something like "be quiet", "you're talking too much" or whatever similar)

Everything else is okay. I committed all the placeholders, but you will have to get the voices from the folder. I'm going out right now so I had to do it really fast using the web editor, sorry about that.

**Comment by P-Chang** [comment]
182000035 is really fit for

PlaySE(4, "ps2/s03/17/142000005", 128, 64);
OutputLine(NULL, "　ボケぇッ！！」",
NULL, " Idiot!!\"", Line_ModeSpecific);

**Comment by enumag** [comment]
@P-Chang Thanks but that's meant for some completely different scene.

@ItaloKnox Translation fix [here](https://github.com/07th-mod/tatarigoroshi/commit/5539e5772f15b77a3522ce8e644ffb7a0ae69ac1), hope its ok. I added the voices as you said too.

**Comment by ItaloKnox** [comment]
All good. 👍 
I think there's not much to fix anymore, right?

**Comment by enumag** [comment]
@ItaloKnox I certainly hope so. This should be everything for tata_008 save for some minor fixes I'll do myself and missing Teppei sprite which I already created a separate issue for. I might find some issues in the rest of the scripts but those should be relatively minor compared to the hell we had to fix here. Thanks for your patience with my perfectionalism!

**Comment by enumag** [comment]
@P-Chang You were able to find some old japanese higurashi gameplay videos before, right? Could you check them to see if the Tatarigoroshi prologue (when Rina's body is found) has voices on PS2 or not?

**Comment by enumag** [comment]
@ItaloKnox The text and the voices didn't match for one of Irie's lines, they were kind of swapped. I tried to change the translation accordingly. Can you check it please? https://github.com/07th-mod/tatarigoroshi/pull/29/commits/82b295ac4c37a082649eaca6d13d3b627c1fe4f8

Also I finally finished tata_008. Please checkout the placeholders branch, pull the latest version (I added a few more missing voices) and add all the voices in that branch to the voice patch. When you're done with that, merge this pull request. I made sure that it has all the fixes but no voices.

If there are any more voices to be added later, I don't think there will be too many so we can just commit them to this repo like normal.

**Comment by ItaloKnox** [comment]
I think you got it perfectly! This should be good enough already, anything else would be nitpicking.

I just got home but I'll push a new patch in a few moments, shouldn't take long. Will update here as soon as I finish it.

**Comment by enumag** [comment]
Great. :-) When you're done with the voice patch and when this PR is merged I think it will be a good time for ADV-release for Tata. (If you or Grelo manage to add the Teppei sprites before the release, it would be even better.)

I have a vacation next weekend so I won't be able to work on Higurashi until about the middle of August. Which works out nicely for me because after all of this I really need a break. This took insane amount of time even with you doing most of the voice searching.

**Comment by ItaloKnox** [comment]
Updated everything, just waiting for you to merge it and give the finishing touches to the master. I'll release the update tomorrow, I'm a little busy today. 😓 

Also you deserve the vacation. Enjoy it! I think we don't have any big issues to take care for now, so don't worry about us. 😆

**Comment by enumag** [comment]
I already did what was needed in this PR. And I just merged it. You can go on whenever you feel like it. ;-)

**Comment by enumag** [comment]
@ItaloKnox Nice to see the release! I just fixed a "typo" in the changelog - we actually added over 200 voices. :-P  It was over 100 in tata_008 alone and another 100 in the rest of the game.

**Comment by ItaloKnox** [comment]
Holy crap, I can't believe we did that much. Makes me wonder what happened back then, I guess we matured a lot. Just think how much further we can go until the very last chapter, I'm looking forward to it.

**Comment by enumag** [comment]
My guess is that back then you thought the later versions were censored because most of the missing voices were abuse-related and it never occured to you to check the PS2 version. I didn't expect PS2 to have the voices either. It was pure luck that I found out.

Honestly though, none of the things we accomplished recently would have been possible for any of us individually. It only works because we have such a great team. It seems I kind of triggered an avalanche when I wrote the compiler because that's when all our recent activity started.

**Comment by ItaloKnox** [comment]
Agreed! I couldn't ask for a better team and I'm glad we could make something this good together. This mod is everywhere, and people seem to really enjoy it. I'm really happy we can keep improving it more and more and still get recognized by our efforts. We still have a couple years ahead to finish it, but when we do I hope we can be fully satisfied with what we have done.

**Comment by enumag** [comment]
Everywhere? I never saw many webpages discussing it. But then again I hardly ever looked. Do you announce our new releases somewhere outside of github?

I wonder how many years it will be. MG seems to have some plans even after Matsuribayashi. And those plans don't even include translation of all the console arcs so it may still not end there. Considering everything we did already I don't think we can be dissatisfied. But I'm really curious about what will our final versions look like.

**Comment by jwgrlrrajn** [comment]
What I'd really like to be able to do eventually is mod the sprites to better match the original designs to some extent. Like, for instance, Mion's missing airsoft holster.

**Comment by ItaloKnox** [comment]
Just try searching for screenshots and videos of the game. You'll find lots and lots of stuff using our mod. Everytime we get a new release a forum thread also comes up hyping the patch, and even pirated copies seem to be bundling our patch. 😆

**Comment by enumag** [comment]
Nice! Forum thread where? Something on Reddit? I don't really like having the patches bundled with pirate copies but there is no way to avoid that.

**Comment by ItaloKnox** [comment]
Steam, I mean! I usually only check reddit for Overwatch and GameDeals, so I don't know what they say about us there, but I'm sure there must be something.

I also feel the same way, I don't think it's right but I also don't want to do anything to avoid this. If people want to pirate the game, it's not really our choice to stop them or not. As long as they are not bringing issues of the pirated version to us, I'm fine.

**Pull request merged**
