### PR TITLE
tata-012 fork

### PR DESCRIPTION
**Pull request by enumag**
@P-Chang Here is another mild censorship candidate for a fork - the voices I added probably don't match the text. I assume you want me to report cases like this, right?

### CODE REVIEW

**Comment by P-Chang** [comment]
https://github.com/07th-mod/tatarigoroshi/commit/b82ad394d16920fe7dd347796463b0d18c193f43
Thank you, I finished it.

**Comment by enumag** [comment]
@P-Chang Thanks! By the way I noticed you added forks to Watanagashi, possibly other chapters. Are these forks missing translations too? If so, can you mark such lines so that @ItaloKnox or @DoctorDiablo can go through them easily in a batch?

**Comment by P-Chang** [comment]
These changes in watanagashi are for just including name line and line break.
And adding name lines in uncensored lines. And fixing some double quotation and　"「」" .

I decided GCensor branch must have name to line break or Line_Normal or LinemodeSp for I don't break your scripts.

**Comment by enumag** [comment]
Are you sure? When I compare some of the zwata files there are quite a few cases with the japanese text being different for each branch but english test being the same... Is there really no need for translation?

**Comment by P-Chang** [comment]
Hmm, these are just merge from Norgus changes.

Probably, he translated almost dialogs that must be.
Dialogs that he leaved are seems like have only one or two word difference, or completely broken Japanese for nuance.

If I increase change, I'll add comment. but Judging old changes are bit hard for me.

After fixing current issue, if I can find missing translation, I'll add comment.

**Comment by ItaloKnox** [comment]
Shouldn't it be easier to compare commits instead of going through the translation again?

**Comment by enumag** [comment]
If these are all changes by Norgus then it's fine. I trust his judgement.

**Comment by P-Chang** [comment]
@ItaloKnox 
Sure. these branch file in chapter2 have all translation of previous version.
And files of chapter1 that I'll make it in future have these too.

**Comment by enumag** [comment]
@P-Chang What needs to be done here? Do we just need to fix the translation?

**Comment by P-Chang** [comment]
@enumag 
If you want to make it perfect, translation is needed.
But scene and dialog flow don't have big difference, there is no need to rush.

**Pull request merged**
