### PR TITLE
ModEnableNVLModeInADVMode issues

### LINKED ISSUE #46: Too long announcer lines
Since the auto-mode is finally usable with voices I was careful to properly fix cases where 1 voice line was split to 2 text lines. (Because the text was stuck on the first line and the second line only showed when the voice was finished.)

I fixed all of these cases I could find in Tatarigoroshi. The only problem is the lines by Announcer in tata_014. The problem is that these lines are really really long and the text does not fit on one screen in ADV-mode.

I can think of 3 possible ways to fix this:
1. Decrease the font-size so that the text fits (this is what I did but I don't really like it).
2. Split the long voice lines to 2 or more so that we can split the text as well. (Not sure if this would work, some of the sentences are really long)
3. Force NVL-mode for that part of the game.

What do you think? To understand the problem it's actually best to try tata_014 by yourself in the game and pay attention to the lines by Announcer. You'll see what I mean.

### PR DESCRIPTION
**Pull request by enumag**
@P-Chang I'd like to fix #46 by forcing NVL mode for that part of the game. It doesn't work as I expected though.

1. The `windo_filter.png` for that we have NVL mode is not used.
2. It seems that `GetGlobalFlag(GADVMode)` still returns true which messes up the intended screen breaks.
3. The text positioning is different than in normal NVL mode - but I should be able to fix that myself in init.txt.

### CODE REVIEW

**Comment by P-Chang** [comment]
It can't use  GLinemodeSp flag for screenbreak because I use it for detect this mode in save and load, so you need replace these to Line_WaitForInput.

Although, name line is not needed in this mode.

If replacing GLinemodeSp have trouble with your scripts, I'll make another logic, but it need your idea.

You can use ModNVLADVModeSettingLoad that was writed in init.txt. and I think current setting is not good one, but NVLMode and NVLADVMode need bit different setting for better looking.

**Comment by enumag** [comment]
Ok I think I'll just remove all conditions for ADV-mode in that part. That should solve the issues with  GLinemodeSp and GADVMode because they won't be there.

So the only thing I think I need from you is to solve the `windo_filter` thing. Is that possible?

**Comment by P-Chang** [comment]
I put windo_filter_nvladv.png( edited vanilla one ) in test edit, so I think current mod CG folder have it, if you change it that you want, it should be change.

But I think current filter are good in this mode, I bit forget about scene that you are working now. I made it for Oni opening scene and Ending and Tips Typewriter and Note scene.

vanilla filter make all to darker so I dislike it, but scene that need this mode are dark scene and don't have character sprite.

How do you think of it?

**Comment by enumag** [comment]
Ok I'll leave it as is for now. Thanks!

**Pull request merged**
